name: Go

on:
  push:
    branches: [ "main" ]
    paths:
      - 'api-go-pgsql'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'api-go-pgsql'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go run .\api-go-pgsql\scripts\main.go

#    - name: Test
#     run: go test -v ./...
